Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/bento-mdf-5wzwN5f9-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
shoulder = terms[("Shoulder", "ICDC")]
shoulder.get_attr_dict()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[33], line 1[0m
[0;32m----> 1[0m shoulder [38;5;241m=[39m [43mterms[49m[43m[[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mShoulder[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mICDC[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m][49m
[1;32m      2[0m shoulder[38;5;241m.[39mget_attr_dict()

[0;31mKeyError[0m: ('Shoulder', 'ICDC')

